services:
  elk-logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: elk-logstash
    restart: unless-stopped
    user: root
    volumes:
      - elk-certs:/usr/share/logstash/certs
      - './logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro'
    networks:
      - elk-network
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

volumes:
  elk-certs:
    external: true
    name: elk-certs

networks:
  elk-network:
    name: elk-network
    external: true
