services:
  elk-kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: elk-kibana
    restart: unless-stopped
    ports:
      - 5050:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elk-es01:9200,http://elk-es02:9200,http://elk-es03:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - TELEMETRY_ENABLED=false
    networks:
      - elk-network

networks:
  elk-network:
    name: elk-network
    external: true
